name: main

on:
  push:
    branches: [main]
    paths:
    - '**'
    - '!.github/workflows/**/*'
    - '.github/workflows/main.yaml'
    - '!README.md'

env:
  UKC_TOKEN: ${{ secrets.UKC_TOKEN }}
  UKC_METRO: ${{ secrets.UKC_METRO }}
  KRAFTKIT_LOG_LEVEL: debug
  KRAFTKIT_NO_CHECK_UPDATES: "true"

permissions:
  deployments: write
  contents: read

jobs:
  deploy:
    environment:
      name: main
      url: https://unikraft.org
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Validate required secrets
      shell: bash
      run: |
        if [[ -z "${{ secrets.UKC_METRO }}" ]]; then
          echo "Missing UKC_METRO secret" >&2
          exit 1
        fi

    - name: Setup KraftKit
      uses: ./.github/actions/setup-kraftkit

    - name: Setup OSS docs website
      id: www
      uses: ./.github/actions/setup-www
      continue-on-error: true
      with:
        environment: main
        name: oss-www
        domain: unikraft.org
        metro: ${{ secrets.UKC_METRO }}
        log-level: trace

    - uses: chrnorm/deployment-action@v2
      name: Create GitHub deployment
      if: always()
      id: deploy-github
      with:
        token: '${{ github.token }}'
        environment-url: 'https://${{ steps.www.outputs.domain }}'
        environment: main

    - name: Update deployment status (success)
      if: ${{ steps.www.outcome == 'success' }}
      uses: chrnorm/deployment-status@v2
      with:
        token: '${{ github.token }}'
        environment-url: 'https://${{ steps.www.outputs.domain }}'
        deployment-id: '${{ steps.deploy-github.outputs.deployment_id }}'
        state: 'success'

    - name: Update deployment status (failure)
      if: ${{ steps.www.outcome == 'failure' }}
      uses: chrnorm/deployment-status@v2
      with:
        token: '${{ github.token }}'
        environment-url: 'https://${{ steps.www.outputs.domain }}'
        deployment-id: '${{ steps.deploy-github.outputs.deployment_id }}'
        state: 'failure'

    - name: Fail job if deploy failed
      if: ${{ steps.www.outcome == 'failure' }}
      shell: bash
      run: |
        exit 1
